import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import { AgentRole } from '@agentic-swarm/shared';

export interface BuildRequest {
  title: string;
  description: string;
  applyToPlatform?: boolean;
}

export interface PlanTask {
  id: string;
  description: string;
  owner: AgentRole;
  dependencies: string[];
}

export interface Plan {
  requestId: string;
  title: string;
  tasks: PlanTask[];
}

const REPO_ROOT = path.resolve(import.meta.dirname, '..', '..', '..');

/**
 * Orchestrator coordinates specialist agents for build requests.
 */
export class Orchestrator {
  /**
   * Run a full build-request cycle.
   */
  async run(requestPath: string): Promise<void> {
    const raw = await fs.readFile(requestPath, 'utf-8');
    const request: BuildRequest = JSON.parse(raw);
    const requestId = crypto.randomUUID().slice(0, 8);

    // 1. Generate plan
    const plan = this.generatePlan(request, requestId);
    await this.storePlan(plan);

    // 2. Write ADR
    await this.writeAdr(plan);

    // 3. Create solution workspace
    await this.createSolutionWorkspace(requestId, request.title);

    // 4. Dispatch tasks (stub — logs task assignment)
    for (const task of plan.tasks) {
      this.dispatch(task);
    }

    // 5. Verify
    await this.verify();
  }

  /** Build a plan from the request. */
  generatePlan(request: BuildRequest, requestId: string): Plan {
    const tasks: PlanTask[] = [
      { id: `${requestId}-1`, description: `Design architecture for: ${request.title}`, owner: AgentRole.ARCHITECT, dependencies: [] },
      { id: `${requestId}-2`, description: 'Implement backend API', owner: AgentRole.BACKEND, dependencies: [`${requestId}-1`] },
      { id: `${requestId}-3`, description: 'Implement frontend UI', owner: AgentRole.FRONTEND, dependencies: [`${requestId}-1`] },
      { id: `${requestId}-4`, description: 'Security review', owner: AgentRole.SECURITY, dependencies: [`${requestId}-2`, `${requestId}-3`] },
      { id: `${requestId}-5`, description: 'QA and testing', owner: AgentRole.QA, dependencies: [`${requestId}-2`, `${requestId}-3`] },
    ];
    return { requestId, title: request.title, tasks };
  }

  private async storePlan(plan: Plan): Promise<void> {
    const dir = path.join(REPO_ROOT, 'knowledge-base', 'prompts', 'build-requests', plan.requestId);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(path.join(dir, 'plan.md'), this.planToMarkdown(plan), 'utf-8');
  }

  private planToMarkdown(plan: Plan): string {
    const lines = [`# Plan: ${plan.title}`, '', `Request ID: ${plan.requestId}`, '', '## Tasks', ''];
    for (const t of plan.tasks) {
      lines.push(`- [ ] **${t.id}** (${t.owner}): ${t.description}`);
      if (t.dependencies.length) lines.push(`  - depends on: ${t.dependencies.join(', ')}`);
    }
    return lines.join('\n') + '\n';
  }

  private async writeAdr(plan: Plan): Promise<void> {
    const dir = path.join(REPO_ROOT, 'docs', 'architecture', 'decisions');
    await fs.mkdir(dir, { recursive: true });
    const filename = `ADR-${plan.requestId}.md`;
    const content = [
      `# ADR-${plan.requestId}: ${plan.title}`,
      '',
      '## Status',
      'Proposed',
      '',
      '## Context',
      `Build request: ${plan.title}`,
      '',
      '## Decision',
      'Architecture option selected by orchestrator based on non-negotiables.',
      '',
      '## Consequences',
      'Tasks dispatched to specialist agents per plan.',
      '',
    ].join('\n');
    await fs.writeFile(path.join(dir, filename), content, 'utf-8');
  }

  private async createSolutionWorkspace(requestId: string, title: string): Promise<void> {
    const dir = path.join(REPO_ROOT, 'solutions', '_staging', requestId);
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(
      path.join(dir, 'README.md'),
      `# Solution: ${title}\n\nRequest ID: ${requestId}\n\nGenerated by orchestrator.\n`,
      'utf-8',
    );
  }

  private dispatch(task: PlanTask): void {
    // eslint-disable-next-line no-console
    console.log(`[dispatch] ${task.id} -> ${task.owner}: ${task.description}`);
  }

  private async verify(): Promise<void> {
    // eslint-disable-next-line no-console
    console.log('[verify] Running scripts/verify.mjs …');
    const { execSync } = await import('node:child_process');
    try {
      execSync('node scripts/verify.mjs', { cwd: REPO_ROOT, stdio: 'inherit' });
    } catch {
      // eslint-disable-next-line no-console
      console.warn('[verify] Verify did not pass — self-heal not yet implemented.');
    }
  }
}
